export const SET_PRODUCT = 'SET_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const PRODUCTS_SUBSCRIPTION = 'PRODUCTS_SUBSCRIPTION';
// export const START_PRODUCT = 'START_PRODUCT';
// export const STOP_PRODUCT = 'STOP_PRODUCT';
